"""Add soft delete to user.

Revision ID: 06923c026d73
Revises: 3048588153c3
Create Date: 2026-02-12 12:15:03.395473

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '06923c026d73'
down_revision: Union[str, None] = '3048588153c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('delete_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'delete_at')
    # ### end Alembic commands ###
